from .pacientesSerializers import PacientesSerializer
from .citasSerializers import CitasSerializer
from .tratamientosSerializers import TratamientosSerializer
from .historialSerializers import HistorialSerializer