# Generated by Django 6.0.3 on 2026-03-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial', 'verbose_name_plural': 'Historiales'},
        ),
        migrations.AlterModelOptions(
            name='pacientes',
            options={'ordering': ['nombre'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='descripcion',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='citas',
            unique_together={('fecha', 'hora')},
        ),
    ]
