# Generated by Django 6.0.3 on 2026-03-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_historial_options_alter_pacientes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='telefono',
            field=models.CharField(max_length=13),
        ),
    ]
